"""initial schema

Revision ID: 8561f014dd0b
Revises:
Create Date: 2026-10-07 16:46:35.405985

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8561f014dd0b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("translation_ru", sa.Text(), nullable=True),
        sa.Column("glossary", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passages")),
    )
    with op.batch_alter_table("passages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_passages_slug"), ["slug"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_streak", sa.Integer(), server_default="0", nullable=False),
        sa.Column("longest_streak", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_active_on", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "username = lower(username)", name=op.f("ck_users_username_lowercase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("passage_id", sa.Integer(), nullable=False),
        sa.Column("option_order", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["passages.id"],
            name=op.f("fk_attempts_passage_id_passages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
    )
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attempts_passage_id"), ["passage_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempts_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "uq_attempts_one_open",
            ["user_id", "passage_id"],
            unique=True,
            postgresql_where=sa.text("submitted_at IS NULL"),
            sqlite_where=sa.text("submitted_at IS NULL"),
        )

    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("passage_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["passages.id"],
            name=op.f("fk_questions_passage_id_passages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint(
            "passage_id", "position", name=op.f("uq_questions_passage_id_position")
        ),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sessions_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_options_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_options")),
        sa.UniqueConstraint(
            "question_id", "position", name=op.f("uq_options_question_id_position")
        ),
    )
    with op.batch_alter_table("options", schema=None) as batch_op:
        batch_op.create_index(
            "uq_options_one_correct",
            ["question_id"],
            unique=True,
            postgresql_where=sa.text("is_correct"),
            sqlite_where=sa.text("is_correct"),
        )

    op.create_table(
        "attempt_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_attempt_answers_attempt_id_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["option_id"],
            ["options.id"],
            name=op.f("fk_attempt_answers_option_id_options"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_attempt_answers_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_answers")),
        sa.UniqueConstraint(
            "attempt_id",
            "question_id",
            name=op.f("uq_attempt_answers_attempt_id_question_id"),
        ),
    )
    with op.batch_alter_table("attempt_answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attempt_answers_option_id"), ["option_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempt_answers_question_id"), ["question_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attempt_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attempt_answers_question_id"))
        batch_op.drop_index(batch_op.f("ix_attempt_answers_option_id"))

    op.drop_table("attempt_answers")
    with op.batch_alter_table("options", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_options_one_correct",
            postgresql_where=sa.text("is_correct"),
            sqlite_where=sa.text("is_correct"),
        )

    op.drop_table("options")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_token_hash"))

    op.drop_table("sessions")
    op.drop_table("questions")
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_attempts_one_open",
            postgresql_where=sa.text("submitted_at IS NULL"),
            sqlite_where=sa.text("submitted_at IS NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_attempts_user_id"))
        batch_op.drop_index(batch_op.f("ix_attempts_passage_id"))

    op.drop_table("attempts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("passages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_passages_slug"))

    op.drop_table("passages")
    # ### end Alembic commands ###
