"""passages questions options

Revision ID: b86b94feeb61
Revises: 
Create Date: 2026-10-06 22:51:18.464194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86b94feeb61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('translation_ru', sa.Text(), nullable=True),
    sa.Column('glossary', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passages'))
    )
    with op.batch_alter_table('passages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passages_slug'), ['slug'], unique=True)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], name=op.f('fk_questions_passage_id_passages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('passage_id', 'position', name=op.f('uq_questions_passage_id_position'))
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_options_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_options')),
    sa.UniqueConstraint('question_id', 'position', name=op.f('uq_options_question_id_position'))
    )
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.create_index('uq_options_one_correct_per_question', ['question_id'], unique=True, postgresql_where=sa.text('is_correct'), sqlite_where=sa.text('is_correct'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_index('uq_options_one_correct_per_question', postgresql_where=sa.text('is_correct'), sqlite_where=sa.text('is_correct'))

    op.drop_table('options')
    op.drop_table('questions')
    with op.batch_alter_table('passages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passages_slug'))

    op.drop_table('passages')
    # ### end Alembic commands ###
